name: inventora_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.66.0
<<<<<<< HEAD
=======
  http: ^1.2.1
  provider: ^6.1.2 # O la versiÃ³n mÃ¡s reciente
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
>>>>>>> origin/main
  cupertino_icons: ^1.0.8
  http: ^1.2.1  # ğŸ‘ˆ agregado correctamente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/inventora_logo.jpeg
